# Generated by Django 4.2 on 2023-04-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precision", models.IntegerField()),
                ("recall", models.IntegerField()),
                ("fluency", models.FloatField()),
                ("conciseness", models.FloatField()),
                ("inclusion", models.FloatField()),
                (
                    "caption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="captions.caption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caption",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="captions.image"
            ),
        ),
    ]
