# Generated by Django 4.2 on 2023-04-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("captions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("comment", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="caption",
            name="model",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="captions.captionmodel",
            ),
            preserve_default=False,
        ),
    ]
